package(default_visibility = ["//visibility:public"])

cc_library(
  name = "iterables",
  srcs = [],
  hdrs = ["permutation.h"],
)

cc_test(
  name = "permutation_test",
  srcs = ["permutation_test.cpp"],
  deps = [
      "@gtest//:main",
      ":iterables"
      ],
)

